version: 1
# datastore:
#   user: user
#   password: password
#   hostname: restapi.eastus2.cloudapp.azure.com
#   port: 3306
#   db: events
datastore:
  user: root
  password: MyPassword1!
  hostname: localhost
  port: 3306
  db: events