---
openapi: 3.0.0
info:
  title: Job Searching API
  description: This API recieves temperature from user
  contact:
    email: mjantsan@my.bcit.ca
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
tags:
  - name : temperature
    description: Operations available for Temperature readings
paths:
  /readings/temperature:
    post:
      tags:
        - temperature
      summary: reports a outside temperature
      operationId: app.report_outside_temperature
      description: Adds a new outside temperature reading to the database
      responses:
        '201':
          description: 'temperature object created'
        '400':
          description: 'Invalid input, object invalid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Temperature'
        description: Temperature item to add
components:
  schemas:
    Temperature:
      required:
        - temperature_id
        - temperature
        - year
        - month
        - day
        - hour
      properties:
        temperature_id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        temperature:
          type: string
          example: 35.7
        year:
          type: integer
          example: 2022
        month:
          type: integer
          example: 2
        day:
          type: integer
          example: 13
        hour:
          type: integer
          example: 03
      type: object